name: Continuous Integration
on: # this determines when this workflow is run
  push:
  #   branches: [ master, melodic-devel ] #  when master or melodic-devel branch is pushed to
  #   pull_request:
  #   branches: [ master ] # when there is a pull request against master
  schedule: # uncomment to run periodically
   - cron: '*/30 * * * *' # every day at 4 AM (UTC)
  workflow_dispatch: # allow manually starting this workflow

jobs:
  curl:
    name: Curl Thread Count=${{matrix.threads}} File=${{matrix.size}}
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        threads: [1, 2, 4, 8, 16]
        size: [15MB, 30MB, "500MB", "file-1GB", "files-5GB-zip"]
      
    steps:
      - name: Setup Curl
        run: sudo apt-get install curl

      - name: Curl
        run: curl -v --trace-time https://link.testfile.org/${{matrix.size}}
        